require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'InterviewPrep' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'GoogleUtilities'
  pod 'TTGTagCollectionView'
  pod 'Masonry'
  pod 'SVPullToRefresh'
  pod 'DragAndDropTableView', '~> 0.1'
  pod 'IQKeyboardManager'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
#  pod 'Firebase/Auth'
#  pod 'Firebase/Firestore'
  

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  
  post_install do |installer|
      installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
              end
          end
      end
  end

  
  
  # Uncomment the code below to enable Flipper.
  #
  # You should not install Flipper in CI environments when creating release
  # builds, this will lead to significantly slower build times.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work.
  #
  #  use_flipper!
  #  post_install do |installer|
  #    flipper_post_install(installer)
  #  end
end
